import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    screenContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'red',
        borderWidth: 0,
    },
    sectionContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        borderColor: 'green',
        borderWidth: 0,
        backgroundColor: 'white',
        width: '85%',
        height: '100%',
        paddingHorizontal: 30,
        borderRadius: 20,
        marginBottom: 40,
        marginTop: 90,
        paddingVertical: 20,
    },
    awardListContainer: {
        borderColor: 'white',
        borderWidth: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        rowGap: 20,
        flexWrap: 'wrap',
        width: '85%',
    },
    acheivementPressable: {
        borderWidth: 0,
        borderColor: 'red',
        width: '40%',
    },
    awardContainer: {
        marginTop: 10,
        borderColor: 'green',
        borderWidth: 0,
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        width: '40%',
    },
    trophyFrame: {
        borderColor: 'lightgrey',
        borderWidth: 0,
        width: 120,
        height: 120,
        padding: 25,
        borderRadius: 70,
        borderWidth: 5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    awardFrame: {
        marginTop: 10,
        borderColor: 'white',
        borderWidth: 0,
        borderRadius: 5,
        borderWidth: 2,
        fontWeight: 'bold',
        fontSize: 18,
        textAlign: 'center',
    },
    lottie: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 1000,
        pointerEvents: 'none',
    }
})

export default styles;